const {chromium}=require('playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true});const page=await browser.newPage({viewport:{width:1440,height:1060}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.resolve(__dirname,'../index.html').replaceAll('\\','/'));await page.selectOption('#playerCount','5');await page.click('#startBtn');assert(await page.locator('#veil').isVisible());assert.equal(await page.locator('.handcard').count(),0);await page.click('#unlockBtn');assert.equal(await page.locator('.handcard').count(),6);assert(await page.locator('.identity').isVisible());
await page.evaluate(()=>{game.s.players[game.s.current].hand[0]={kind:'path',shape:'ew',id:900};render()});await page.locator('.handcard').first().click();assert(await page.locator('.cell.legal').count()>0);await page.locator('.cell.legal[data-x="1"][data-y="0"]').click();assert(await page.locator('#veil').isVisible());assert.equal(await page.locator('.identity').count(),0);assert.equal(await page.locator('.handcard').count(),0);await page.click('#unlockBtn');
// View a map privately; the next player's panel must stay blank until handoff.
await page.evaluate(()=>{game.s.players[game.s.current].hand[0]={kind:'map',id:901};render()});await page.locator('.handcard').first().click();await page.locator('.cell.target[data-x="8"][data-y="0"]').click();assert(await page.locator('#peek').isVisible());assert.equal(await page.locator('.identity').count(),0);await page.click('#closePeek');assert(await page.locator('#veil').isVisible());assert.equal(await page.locator('#peekContent').textContent(),'');await page.click('#unlockBtn');assert.equal(await page.locator('.known').count(),0);
let turn=await page.evaluate(()=>game.s.turn);await page.reload();assert(await page.locator('#veil').isVisible());assert.equal(await page.locator('.handcard').count(),0);assert.equal(await page.evaluate(()=>game.s.turn),turn);await page.click('#unlockBtn');
// Gold discovery and private draft all use the real UI controls.
await page.evaluate(()=>{let s=game.s;s.current=0;s.players.forEach((p,i)=>p.role=i===1?'saboteur':'miner');for(let x=1;x<7;x++)s.board[key(x,0)]={kind:'path',shape:'ew',x,y:0,rot:0};s.board['8,0'].content='gold';s.players[0].hand[0]={kind:'path',shape:'ew',id:902};revealed=true;selected=-1;render()});await page.locator('.handcard').first().click();await page.locator('.cell.legal[data-x="7"][data-y="0"]').click();assert.equal(await page.evaluate(()=>game.s.phase),'roundEnd');assert.equal(await page.locator('.rolepublic').count(),5);await page.locator('#roundActions button').click();assert(await page.locator('#veil').isVisible());assert.equal(await page.locator('.goldcard').count(),0);for(let i=0;i<4;i++){await page.click('#unlockBtn');assert(await page.locator('.goldcard').count()>0);await page.locator('.goldcard').first().click()}assert.equal(await page.evaluate(()=>game.s.phase),'between');await page.locator('#roundActions button').click();assert.equal(await page.evaluate(()=>game.s.round),2);assert(await page.locator('#veil').isVisible());await page.click('#unlockBtn');assert.equal(await page.locator('.rolepublic').count(),0);
// Fresh playable illustration, with a small legal network and all three goals.
await page.evaluate(()=>{game=new Game(5);for(let x=1;x<=3;x++)game.s.board[key(x,0)]={kind:'path',shape:'ew',x,y:0,rot:0};game.s.board['4,0']={kind:'path',shape:'new',x:4,y:0,rot:0};game.s.board['4,-1']={kind:'path',shape:'nes',x:4,y:-1,rot:0};game.s.lastPlaced='4,-1';game.s.players[0].hand=[{kind:'path',shape:'cross'},{kind:'path',shape:'ne'},{kind:'repair',tools:['pick','lamp']},{kind:'map'},{kind:'break',tools:['cart']},{kind:'fall'}];game.s.players[0].role='miner';revealed=true;selected=0;rotation=0;render();fit()});assert(await page.locator('img').evaluateAll(imgs=>imgs.every(im=>im.complete&&im.naturalWidth>0)));await page.screenshot({path:path.resolve(__dirname,'../preview-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fit());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.resolve(__dirname,'../preview-mobile.png'),fullPage:true});await page.click('#cardsBtn');assert.equal(await page.locator('.catalogcard').count(),22);await page.locator('#catalog [data-close]').click();await page.click('#lockBtn');assert.equal(await page.locator('.handcard').count(),0);assert.equal(await page.locator('.identity').count(),0);assert.deepEqual(errors,[]);console.log('PASS: setup, placement, private handoff, private map, saved resume, gold draft, next round, catalog, desktop/mobile layout; no browser errors.');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
