'use strict';
const $=q=>document.querySelector(q),{Game,PATHS,TOOLS,DIRS,key,groups,ports,toolName}=MineRules;
const STORAGE='shenkeng-shadow-v1';
let game=null,revealed=false,selected=-1,rotation=0,zoom=68,canSave=true,hasSave=false,toastTimer;
const sum=a=>a.reduce((n,v)=>n+v,0);
function icon(tool){const paths={pick:'<path d="M4 5Q12 0 20 7M12 4L5 21M11 6L19 17"/>',lamp:'<path d="M8 7V4h8v3M6 8h12l2 12H4ZM9 12v5m6-5v5"/>',cart:'<path d="M3 6h18l-3 10H6ZM6 20h1m10 0h1M8 3l3 3m5-4-2 4"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[tool]+'</svg>'}
function assetCode(c){
 if(c.start)return 'S01';if(c.goal)return !c.open?'back-secret':c.content==='gold'?'G01':c.content==='rockA'?'G02':'G03';
 if(c.kind==='path')return c.code||'P'+String(PATHS.find(p=>p.id===c.shape).first).padStart(2,'0');
 if(c.kind==='map')return 'A22';if(c.kind==='fall')return 'A19';
 let ts=c.tools||[],n=c.kind==='break'?1+TOOLS.indexOf(ts[0])*3:ts.length===1?10+TOOLS.indexOf(ts[0])*2:ts.includes('pick')?(ts.includes('lamp')?16:17):18;
 return 'A'+String(n).padStart(2,'0');
}
function art(c){return '<span class="cardart"><img src="'+ASSETS[assetCode(c)]+'" alt="'+cardName(c)+'" draggable="false" style="transform:rotate('+(c.rot===2?180:0)+'deg)">'+(c.goal?'<span class="goal-label">'+c.label+'</span>':'')+'</span>'}
function cardName(c){if(c.start)return '渡船頭集合點';if(c.goal)return '目標 '+c.label+(c.open?'・'+(c.content==='gold'?'文化箱':'空點'):'・尚未翻開');if(c.kind==='path')return PATHS.find(p=>p.id===c.shape).name;return c.kind==='map'?'街坊線索':c.kind==='fall'?'工區拆除':(c.kind==='break'?'破壞':'修復')+'・'+c.tools.map(toolName).join('／')}
function cardText(c){if(c.kind==='path')return MineRules.shape(c).dead?'只有一個入口，路在紅色橫槓處終止。入口必須接回渡船頭。':'各個出口彼此連通。僅可旋轉 180°，所有已知相鄰邊需吻合。';return {break:'選一位玩家（包括自己）使裝備故障。不能重複破壞同一工具。',repair:'選擇一項已損壞工具修復；雙工具牌也只能修一項。',map:'點選 A、B 或 C，秘密查看尚未翻開的藏寶點。',fall:'點選一般道路移除。集合點與目標不可移除。'}[c.kind]}
function selectedCard(){return revealed&&game.s.phase==='turn'?game.s.players[game.s.current].hand[selected]:null}
function save(){if(!game)return;try{localStorage.setItem(STORAGE,JSON.stringify(game.s));hasSave=true;canSave=true}catch(e){canSave=false}}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
function seal(){revealed=false;selected=-1;rotation=0;render();showVeil()}
function showVeil(){let s=game.s;if(!['turn','award'].includes(s.phase)){ $('#veil').hidden=true;return }$('#veilTitle').textContent='請交給 '+s.players[s.current].name;$('#veilText').textContent=s.phase==='award'?'現在輪到你秘密選取文化點卡。請其他玩家移開視線。':'請其他玩家移開視線，再查看身分與手牌。';$('#veil').hidden=false}
function unlock(){revealed=true;selected=-1;$('#veil').hidden=true;render();if(innerWidth<761)$('#turnTitle').scrollIntoView({block:'start',behavior:'auto'})}
function act(fn){try{fn();save()}catch(e){toast(e.message)}}
function play(action){act(()=>{let out=game.play(selected,action);revealed=false;selected=-1;rotation=0;save();render();if(out.info){$('#peekContent').innerHTML='<div class="peek-result">藏寶點 '+out.info.label+'<br>'+(out.info.content==='gold'?'◆ 四寶文化箱':'⬟ 空點')+'</div>';$('#peek').showModal()}else showVeil()})}
function addButton(parent,text,fn,cls=''){let b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;parent.append(b);return b}
function render(){if(!game)return;let s=game.s,p=s.players[s.current],publicRoles=['roundEnd','award','between','over'].includes(s.phase),c=selectedCard();$('#roundTitle').textContent=s.phase==='over'?'尋寶結束 · 最終排名':'第 '+s.round+' / 3 回合';$('#roundPips').innerHTML='<b class="pips">'+[1,2,3].map(i=>i<=s.round?'◆':'◇').join('')+'</b>';$('#deckInfo').textContent='牌庫 '+s.deck.length+' 張';$('#players').innerHTML=s.players.map((p,i)=>'<div class="player '+(i===s.current&&['turn','award'].includes(s.phase)?'current':'')+'"><div class="row"><strong>'+p.name+'</strong><span class="badge">'+p.hand.length+' 張</span></div><div class="tools">'+TOOLS.map(t=>'<span class="tool '+(p.broken.includes(t)?'broken':'')+'" title="'+toolName(t)+(p.broken.includes(t)?'損壞':'正常')+'" aria-label="'+toolName(t)+(p.broken.includes(t)?'損壞':'正常')+'">'+icon(t)+'</span>').join('')+'</div>'+(publicRoles?'<div class="rolepublic">'+(p.role==='miner'?'◆ 導覽隊':'✕ 暗影隊')+'</div>':'')+'</div>').join('');
 $('#turnTitle').textContent=s.phase==='turn'?p.name+' · 第 '+s.turn+' 手':s.phase==='award'?p.name+' · 選取文化點':s.phase==='over'?'三回合總結':'本回合結果';
 $('#status').textContent=s.phase==='turn'?(revealed?(c?'已選：'+cardName(c):'選一張手牌，鋪路或使用行動。'):'手牌已遮蔽，等待玩家接手。'):s.phase==='award'?'導覽隊逆時針選文化點，每人一張。':s.phase==='over'?'文化點最多的玩家獲勝；同分共享勝利。':s.winner==='miner'?'文化箱已接通，導覽隊獲勝！':s.players.some(p=>p.role==='saboteur')?'手牌耗盡，暗影隊獲勝。':'手牌耗盡且沒有暗影隊，本回合無人得分。';
 $('#privatePanel').innerHTML=revealed&&['turn','award'].includes(s.phase)?'<div class="identity '+p.role+'"><img class="role-art" src="'+ASSETS[p.role==='miner'?'R01':'R08']+'" alt="你的身分牌"><span class="eyebrow">你的秘密身分</span><b>'+(p.role==='miner'?'◆ 導覽隊':'✕ 暗影隊')+'</b><p>'+(p.role==='miner'?'讓集合點與真正的文化箱相通。':'讓所有手牌用完前，都沒人接通文化箱。')+'</p><div class="gold">你的累積文化點：'+sum(p.gold)+' 點</div></div>'+(Object.keys(p.known).length?'<div class="known">你的尋寶筆記：'+Object.entries(p.known).map(([k,v])=>k+' '+(v==='gold'?'文化箱':'空點')).join(' · ')+'</div>':''):'';
 $('#selection').innerHTML=c?'<div class="selection"><h3>'+cardName(c)+'</h3><p>'+cardText(c)+'</p></div>':'';
 let actions=$('#actions');actions.innerHTML='';if(c){if(c.kind==='path'){let disabled=p.broken.length>0;if(disabled){let note=document.createElement('p');note.className='dim';note.textContent='工具損壞：先修復、改出行動牌，或棄牌。';actions.append(note)}let b=addButton(actions,'↻ 旋轉 180°',()=>{rotation=(rotation+2)%4;render()});b.disabled=disabled;let moves=game.pathMoves(c);if(!disabled&&!moves.length){let note=document.createElement('p');note.className='dim';note.textContent='這張牌目前沒有合法位置，可改選牌或棄置。';actions.append(note)}else if(!disabled&&!moves.some(m=>m.rot===rotation))addButton(actions,'轉到可放置的方向',()=>{rotation=moves[0].rot;render()})}else{let targets=game.actionTargets(c);if(['map','fall'].includes(c.kind)){let note=document.createElement('p');note.className='dim';note.textContent=targets.length?'點擊棋盤上金色外框的目標。':'目前沒有可使用的目標。';actions.append(note)}else targets.forEach(t=>addButton(actions,(c.kind==='break'?'破壞 ':'修復 ')+s.players[t.player].name+'・'+toolName(t.tool),()=>play(t)));if(!targets.length&&!['map','fall'].includes(c.kind)){let note=document.createElement('p');note.className='dim';note.textContent='目前沒有可使用的目標。';actions.append(note)}}addButton(actions,'蓋牌棄置這張，結束出牌',()=>play({type:'discard'}),'discard')}
 let ra=$('#roundActions');ra.innerHTML='';if(publicRoles){let note=document.createElement('p');note.className='dim';note.textContent='未發出的身分：'+(s.unusedRole==='miner'?'導覽隊':'暗影隊');ra.append(note)}if(s.phase==='roundEnd')addButton(ra,'確認身分，開始分配文化點 →',()=>act(()=>{game.beginAwards();save();seal()}),'primary');if(s.phase==='between')addButton(ra,'文化點已分配，開始下一回合 →',()=>act(()=>{game.nextRound();save();seal()}),'primary');if(s.phase==='over'){let rank=s.players.map((p,i)=>({i,name:p.name,score:sum(p.gold)})).sort((a,b)=>b.score-a.score),w=rank.filter(p=>p.score===rank[0].score);let div=document.createElement('div');div.innerHTML='<p class="amber">'+w.map(p=>p.name).join('、')+' 獲勝！</p>'+rank.map(p=>'<div class="finalscore"><span>'+p.name+'<small class="score-rounds">'+(s.players[p.i].scores||[]).map((v,i)=>'第'+(i+1)+'回合 '+v).join(' · ')+'</small></span><b>'+p.score+' 點</b></div>').join('');ra.append(div);addButton(ra,'再開一局',()=>$('#setup').showModal(),'primary')}
 $('#handHint').textContent=s.phase==='award'?'私下選一張，剩下的交給下一位導覽隊':'每次出一張，再抽一張';$('#hand').innerHTML='';if(revealed&&s.phase==='turn'){p.hand.forEach((card,i)=>{let b=document.createElement('button');b.className='handcard '+(i===selected?'selected':'');b.setAttribute('aria-label',cardName(card)+'，手牌 '+(i+1));b.setAttribute('aria-pressed',i===selected?'true':'false');b.innerHTML=art({...card,rot:i===selected?rotation:0})+'<span class="n">'+(i+1)+'</span><span class="name">'+cardName(card)+'</span>';b.onclick=()=>{selected=i;rotation=0;render()};$('#hand').append(b)})}else if(revealed&&s.phase==='award'){s.goldPool.forEach((v,i)=>addButton($('#hand'),'◆ '+v+' 點',()=>act(()=>{game.chooseGold(i);save();seal()}),'goldcard'))}else $('#hand').innerHTML='<div class="handplaceholder">'+(['between','roundEnd'].includes(s.phase)?'本回合結束。身分已公開，文化點持續保密。':s.phase==='over'?'三回合尋寶完成。':'◇ 手牌與秘密資訊已遮蔽')+'</div>';
 $('#log').innerHTML=s.log.map(v=>'<p>'+v+'</p>').join('');$('#saveStatus').textContent=canSave?'● 自動存檔於此瀏覽器':'瀏覽器無法存檔；關閉後可能遺失進度';$('#lockBtn').disabled=!['turn','award'].includes(s.phase);renderBoard(c)}
function renderBoard(c){let s=game.s,coords=[...Object.values(s.board),...game.frontier()],minX=Math.min(-1,...coords.map(t=>t.x)),maxX=Math.max(8,...coords.map(t=>t.x)),minY=Math.min(-2,...coords.map(t=>t.y)),maxY=Math.max(2,...coords.map(t=>t.y));let legal=new Set(c?.kind==='path'?game.pathMoves(c).filter(m=>m.rot===rotation).map(m=>key(m.x,m.y)):[]),targets=new Set(c?game.actionTargets(c).filter(t=>t.cell).map(t=>t.cell):[]),board=$('#board');board.style.setProperty('--tile',zoom+'px');board.style.gridTemplateColumns='repeat('+(maxX-minX+1)+','+zoom+'px)';board.innerHTML='';for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){let k=key(x,y),t=s.board[k],valid=legal.has(k),target=targets.has(k),b=document.createElement('button');b.className='cell '+(t?'filled':'empty')+(valid?' legal':'')+(target?' target':'')+(s.lastPlaced===k?' last':'');b.dataset.x=x;b.dataset.y=y;b.disabled=!valid&&!target;b.title=t?cardName(t):(valid?'放置於 ':'空格 ')+k;b.setAttribute('aria-label',b.title);b.innerHTML=t?art(t):valid?'+':'';if(valid)b.onclick=()=>play({x,y,rot:rotation});if(target)b.onclick=()=>play({cell:k});board.append(b)}}
function fit(){let s=game.s,coords=[...Object.values(s.board),...game.frontier()],w=Math.max(8,...coords.map(t=>t.x))-Math.min(-1,...coords.map(t=>t.x))+1,h=Math.max(2,...coords.map(t=>t.y))-Math.min(-2,...coords.map(t=>t.y))+1;zoom=Math.max(24,Math.min(88,Math.floor(($('#viewport').clientWidth-48-(w-1)*4)/w),Math.floor(($('#viewport').clientHeight-48-(h-1)*4)/h/1.4286)));render();$('#viewport').scrollLeft=0;$('#viewport').scrollTop=0}
function catalog(){let cards=PATHS.map(p=>({card:{kind:'path',shape:p.id},count:p.count}));for(let t of TOOLS){cards.push({card:{kind:'break',tools:[t]},count:3},{card:{kind:'repair',tools:[t]},count:2})}for(let tools of [['pick','lamp'],['pick','cart'],['lamp','cart']])cards.push({card:{kind:'repair',tools},count:1});cards.push({card:{kind:'map'},count:6},{card:{kind:'fall'},count:3});$('#catalogContent').innerHTML=cards.map(({card,count})=>'<div class="catalogcard">'+art(card)+'<p>'+cardName(card)+' × '+count+'</p></div>').join('');$('#catalog').showModal()}
$('#unlockBtn').onclick=unlock;$('#lockBtn').onclick=seal;$('#newBtn').onclick=()=>{seal();$('#playerCount').value=game.s.players.length;$('#setup').showModal()};$('#startBtn').onclick=()=>{game=new Game(+$('#playerCount').value);save();$('#setup').close();seal();fit()};$('#cancelSetup').onclick=()=>{$('#setup').close();showVeil()};$('#rulesBtn').onclick=$('#veilRulesBtn').onclick=()=>$('#help').showModal();$('#cardsBtn').onclick=catalog;$('#closePeek').onclick=()=>{$('#peek').close();$('#peekContent').innerHTML='';showVeil()};$('#peek').addEventListener('cancel',e=>{e.preventDefault();$('#closePeek').click()});$('#setup').addEventListener('cancel',e=>{e.preventDefault();$('#cancelSetup').click()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#zoomOut').onclick=()=>{zoom=Math.max(38,zoom-8);render()};$('#zoomIn').onclick=()=>{zoom=Math.min(120,zoom+8);render()};$('#fitBtn').onclick=fit;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game){if($('#peek').open){$('#peek').close();$('#peekContent').innerHTML=''}seal()}});
try{let saved=localStorage.getItem(STORAGE);if(saved){game=Game.restore(JSON.parse(saved));hasSave=true}}catch(e){toast('無法讀取舊存檔，請開新遊戲。')}
if(!game)game=new Game(5);render();showVeil();if(!hasSave)$('#setup').showModal();
